"""
Export Functions Module
=======================
Functions for exporting data to CSV and JavaScript files.
"""

import json
import pandas as pd

from ..config import DATA_OUTPUT_PATH, DASHBOARD_DATA_PATH


def export_master_csv(df: pd.DataFrame, filename: str = "master_transactions.csv"):
    """Export the master DataFrame to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"\n✓ Exported to: {output_path}")
    return output_path


def export_holdings_csv(df: pd.DataFrame, filename: str = "holdings.csv"):
    """Export the holdings DataFrame to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported holdings to: {output_path}")
    return output_path


def export_holdings_detail_csv(df: pd.DataFrame, filename: str = "holdings_detail.csv"):
    """Export detailed holdings with cost basis to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported detailed holdings to: {output_path}")
    return output_path


def export_realized_gains_csv(df: pd.DataFrame, filename: str = "realized_gains.csv"):
    """Export realized gains/losses to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported realized gains to: {output_path}")
    return output_path


def export_tax_lots_csv(df: pd.DataFrame, filename: str = "tax_lots.csv"):
    """Export tax lots detail to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported tax lots to: {output_path}")
    return output_path


def export_income_report_csv(df: pd.DataFrame, filename: str = "income_report.csv"):
    """Export income report to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported income report to: {output_path}")
    return output_path


def export_income_by_year_csv(df: pd.DataFrame, filename: str = "income_by_year.csv"):
    """Export income by year to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported income by year to: {output_path}")
    return output_path


def export_account_summary_csv(df: pd.DataFrame, filename: str = "account_summary.csv"):
    """Export account summary to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported account summary to: {output_path}")
    return output_path


def export_historical_holdings_csv(df: pd.DataFrame, filename: str = "historical_holdings.csv"):
    """Export historical holdings summary to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported historical holdings to: {output_path}")
    return output_path


def export_cash_balances_csv(df: pd.DataFrame, filename: str = "cash_balances.csv"):
    """Export cash account balances to CSV."""
    output_path = DATA_OUTPUT_PATH / filename
    df.to_csv(output_path, index=False)
    print(f"✓ Exported cash balances to: {output_path}")
    return output_path


def export_portfolio_summary_js(summary: dict, filename: str = "portfolio_summary.js"):
    """Export portfolio summary as a JavaScript file to dashboard/data folder."""
    js_content = "// Portfolio data - auto-generated by detectAndClean.py\n"
    js_content += "const portfolioData = "
    js_content += json.dumps(summary, indent=2)
    js_content += ";\n"
    
    # Write to dashboard/data folder only
    output_path = DASHBOARD_DATA_PATH / filename
    with open(output_path, "w") as f:
        f.write(js_content)
    
    print(f"✓ Exported portfolio summary to: {output_path}")
    return output_path


def export_dataframe_js(df: pd.DataFrame, var_name: str, filename: str):
    """Export a DataFrame as a JavaScript file to dashboard/data folder."""
    # Convert DataFrame to list of dicts for JSON serialization
    data = df.to_dict(orient='records')
    js_content = f"// {var_name} - auto-generated by detectAndClean.py\n"
    js_content += f"const {var_name} = "
    js_content += json.dumps(data, indent=2)
    js_content += ";\n"
    
    # Write to dashboard/data folder only
    output_path = DASHBOARD_DATA_PATH / filename
    with open(output_path, "w") as f:
        f.write(js_content)
    
    print(f"✓ Exported {var_name} to: {output_path}")
    return output_path
