"""The shipped sample portfolio must actually be exercised.

`samples/portfolio.snapshot.json` carries all ten broker CSV formats and
is the artifact a new user (or a fork) runs first — but nothing consumed
it. The end-to-end test builds its own inline synthetic portfolio, so
**five of the nine broker parsers had zero executed lines**:
`parse_usaa`, `parse_schwab`, `parse_vanguard_401k`,
`parse_apple_savings` and `parse_coinbase_pro`. Any regression in those
shipped green, and the sample could rot without anyone noticing.

This module closes both gaps at once: it pins the sample as working
input AND gives the five orphaned parsers their first coverage.

Deliberately split into two layers:

* **Parse-level tests** — fast, no pricing, no network. These are what
  actually cover the parsers, and they assert the post-parse invariants
  CLAUDE.md declares (quantity / amount / fees non-negative, direction
  encoded in the action, every action known to the catalog).
* **One end-to-end test** — proves the sample still drives a complete
  run. Slower, so there is exactly one.

Assertions are deliberately *structural* (counts, signs, membership) and
never hard-coded totals: the sample is regenerated by
`tools/build_sample_snapshot.py`, and a test that pins its arithmetic
would break on every legitimate regeneration. Structural assertions
survive that; arithmetic belongs in `test_pipeline_snapshot.py`, whose
fixture is built for it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SAMPLE = ROOT / "samples" / "portfolio.snapshot.json"

# Every broker file the snapshot is expected to carry, mapped to the
# scanner key it must be detected as.  If a future snapshot drops one,
# the parser it covers silently loses its only test — so the mapping is
# asserted, not assumed.
EXPECTED_BROKERS = {
    "apple-savings.csv": "apple_savings",
    "coinbase-1.csv": "coinbase",
    "coinbase-pro-gdax-1.csv": "coinbase_pro",
    "robinhood-1.csv": "robinhood",
    "schwab-roth-ira-1.csv": "schwab_roth",
    "usaa-roth-ira.csv": "usaa",
    "vanguard-401k.csv": "vanguard_401k",
    "voya-401k-1.csv": "voya_401k",
}

# Parsers that had NO test coverage before this module existed.
PREVIOUSLY_ORPHANED = {
    "apple_savings", "coinbase_pro", "schwab_roth", "usaa", "vanguard_401k",
}


@pytest.fixture
def sample_data(isolated_workdir):
    """Restore the sample snapshot into an isolated `data/` directory."""
    from src.snapshot import import_snapshot

    result = import_snapshot(SAMPLE, isolated_workdir / "data", overwrite=True)
    assert result["written"], "snapshot import wrote nothing"
    return isolated_workdir / "data"


class TestSampleSnapshotIsUsable:

    def test_snapshot_file_exists(self):
        assert SAMPLE.exists(), (
            "the shipped sample snapshot is missing — README points new "
            "users at it"
        )

    def test_import_restores_every_broker_file(self, sample_data):
        present = {p.name for p in sample_data.glob("*.csv")}
        missing = set(EXPECTED_BROKERS) - present
        assert not missing, f"sample snapshot lost broker file(s): {sorted(missing)}"

    def test_scanner_detects_each_broker_file(self, sample_data):
        from src.scanner import detect_broker

        wrong = {}
        for name, expected in EXPECTED_BROKERS.items():
            got = detect_broker(sample_data / name)
            if got != expected:
                wrong[name] = f"expected {expected}, got {got}"
        assert not wrong, f"broker detection drifted: {wrong}"

    def test_metadata_and_manual_files_are_skipped(self, sample_data):
        """Config and hand-edit files must never enter the txn pipeline."""
        from src.scanner import detect_broker

        assert detect_broker(sample_data / "metadata.csv") == "skip"


class TestSampleParsesCleanly:
    """These are the tests that give the five orphaned parsers coverage."""

    @pytest.fixture
    def txns(self, sample_data):
        from src.parsers import parse_all_files

        out = parse_all_files(sample_data)
        assert out, "sample portfolio parsed to zero transactions"
        return out

    def test_every_broker_file_yields_transactions(self, txns):
        """A parser returning [] is the silent-row-dropping failure mode —
        high severity, because it under-reports a position with no visible
        symptom."""
        by_source = {}
        for t in txns:
            by_source.setdefault(t.get("source", ""), 0)
            by_source[t["source"]] += 1

        empty = [f for f in EXPECTED_BROKERS if by_source.get(f, 0) == 0]
        assert not empty, (
            f"parsed zero rows from {empty} — either the parser broke or the "
            "sample lost its rows; both are silent in production"
        )

    def test_previously_orphaned_parsers_are_exercised(self, sample_data):
        """Pins the point of this module.

        If a future change stops these files reaching their parsers, the
        five parsers quietly return to zero coverage — which is the exact
        state this module was written to end.
        """
        from src.parsers import _PARSERS
        from src.scanner import detect_broker

        reached = {detect_broker(sample_data / n) for n in EXPECTED_BROKERS}
        assert PREVIOUSLY_ORPHANED <= reached, (
            f"sample no longer reaches {sorted(PREVIOUSLY_ORPHANED - reached)}"
        )
        for key in PREVIOUSLY_ORPHANED:
            assert key in _PARSERS, f"{key} lost its parser registration"

    def test_quantities_amounts_and_fees_are_non_negative(self, txns):
        """CLAUDE.md's central post-parse invariant: direction lives in
        the ACTION, never in the sign. A negative here means a parser
        skipped its `abs()` and downstream sign logic will double-count."""
        bad = [
            (t.get("source"), t.get("date"), t.get("action"), f, t.get(f))
            for t in txns
            for f in ("quantity", "price", "fees", "amount")
            if isinstance(t.get(f), (int, float)) and t[f] < 0
        ]
        assert not bad, f"negative values after parsing: {bad[:5]}"

    def test_every_row_has_the_common_schema(self, txns):
        required = {"date", "account", "symbol", "action", "quantity",
                    "price", "fees", "amount", "description", "source"}
        for t in txns:
            missing = required - set(t)
            assert not missing, f"row missing {sorted(missing)}: {t}"

    def test_dates_are_iso_and_not_in_the_future(self, txns):
        from datetime import date

        today = date.today().isoformat()
        for t in txns:
            d = t.get("date", "")
            assert len(d) == 10 and d[4] == "-" and d[7] == "-", (
                f"non-ISO date {d!r} from {t.get('source')}"
            )
            assert d <= today, f"future-dated row {d} from {t.get('source')}"

    def test_raw_actions_are_non_empty(self, txns):
        """Direction is encoded in the action, so a blank one is
        unclassifiable downstream.

        NOTE: whether each action *normalizes* to a catalog entry is
        deliberately NOT tested here. `normalize.RULES` are scoped by
        `account_group`, which `main.py` attaches after parsing — calling
        `normalize_action` on raw parser output makes every scoped rule
        miss and everything fall through to title-case, which looks like
        a swarm of classification gaps that do not exist. That assertion
        belongs on the exported run; see
        `TestSampleDrivesAFullRun::test_every_exported_action_is_in_the_catalog`.
        """
        blank = [(t.get("source"), t.get("date")) for t in txns
                 if not (t.get("action") or "").strip()]
        assert not blank, f"rows with no action: {blank[:5]}"


class TestSampleDrivesAFullRun:
    """One end-to-end test. Slower than the parse-level ones, so there is
    exactly one — it proves the sample still produces a dashboard, not
    that any particular figure is right."""

    # The underlying of the sample's OPEN option contract. Seeded so the
    # intrinsic floor has something to floor AGAINST — with an empty
    # cache the contract falls back to its purchase premium and the
    # floor never engages, which would make the test below vacuous.
    UNDERLYING_PRICE = 400.0
    OPEN_STRIKE = 250.0

    @pytest.fixture
    def exported(self, isolated_workdir, sample_data, stub_prices):
        import json
        import sys
        from datetime import date, timedelta

        from src.prices import ensure_coverage

        today = date.today()
        series = {(today - timedelta(days=n)).isoformat(): self.UNDERLYING_PRICE
                  for n in range(0, 400, 7)}
        stub_prices.set("AAPL", series)
        stub_prices.set_sector("AAPL", "Technology")
        ensure_coverage([("AAPL")], today - timedelta(days=400), today)

        argv_save = sys.argv
        sys.argv = ["fin", "--skip-rename"]
        try:
            from src.main import main
            main()
        finally:
            sys.argv = argv_save

        txn_json = isolated_workdir / "exports" / "transactions.json"
        assert txn_json.exists(), "pipeline produced no transactions.json"
        return json.loads(txn_json.read_text(encoding="utf-8"))

    def test_every_exported_action_is_in_the_catalog(self, exported):
        """An action with no normalize rule is title-cased and passed
        through silently — taxonomy (5), a classification gap landing on
        a default. Checked on the EXPORT, where `account_group` exists
        and the scoped rules can actually match.
        """
        from src.actions import ACTION_COLORS

        catalog = set(ACTION_COLORS)
        unknown = sorted({
            (t.get("source"), t.get("action"))
            for t in exported["transactions"]
            if t.get("action") not in catalog
        })
        assert not unknown, (
            f"exported actions with no catalog entry: {unknown} — each is a "
            "broker action string that fell through normalize.RULES"
        )

    def test_wrap_carries_basis_instead_of_realizing_it(self, exported):
        """ETH -> CBETH -> sell, end to end.

        Wrap/unwrap is basis-CARRYING: the pair moves the same
        underlying, so neither leg realizes gain and the destination
        inherits the source's basis rescaled to the new quantity. Gain
        appears only at the eventual real sale. CLAUDE.md calls this the
        rule that has broken most often — mapping it to Buy/Sell (the old
        behaviour) realized the whole gain at every wrap.

        Added to the sample deliberately: before it existed, no
        end-to-end path reached this code at all.
        """
        txns = exported["transactions"]
        out = [t for t in txns if t.get("action") == "Wrap Asset Out"]
        into = [t for t in txns if t.get("action") == "Wrap Asset In"]
        assert out and into, "the sample no longer contains a wrap pair"

        for leg in out + into:
            assert not leg.get("realized_gain"), (
                f"{leg['action']} realized {leg.get('realized_gain')} — a wrap "
                "is not a disposal; gain belongs at the eventual sale"
            )

        # The destination inherits the source's basis, not $0 and not the
        # full market value.
        assert into[0]["cost_basis"] == pytest.approx(out[0]["cost_basis"]), (
            "the wrapped asset did not inherit the source lot's basis"
        )

        sells = [t for t in txns
                 if t.get("action") == "Sell" and t.get("symbol") == "CBETH-USD"]
        assert sells, "no CBETH sale — the carried basis is never observed"
        sell = sells[0]
        assert sell["cost_basis"] == pytest.approx(into[0]["cost_basis"]), (
            "the sale relieved a different basis than the wrap carried"
        )
        assert sell.get("realized_gain"), (
            "the sale realized nothing — carried basis should produce a gain"
        )

    def test_a_stock_split_preserves_total_basis(self, exported):
        """A broker `Stock Split` row reaches `Split`, whose basis effect
        rescales lot quantity and per-share basis while leaving TOTAL
        basis alone.

        Also added deliberately: `basis._apply_split_to_lots` and
        history's inline copy of the same arithmetic were both
        never-executed before this row existed (F-002 / F-015).
        """
        txns = exported["transactions"]
        splits = [t for t in txns if t.get("action") == "Split"]
        assert splits, "the sample no longer contains a stock split"
        sym = splits[0]["symbol"]

        bought = sum(t.get("quantity", 0) for t in txns
                     if t.get("symbol") == sym and t.get("action") == "Buy")
        added = sum(t.get("quantity", 0) for t in splits)

        holding = [h for h in exported["holdings_by_account"]
                   if h["symbol"] == sym]
        assert holding, f"{sym} is missing from holdings after the split"

        cost = sum(abs(t.get("amount", 0)) for t in txns
                   if t.get("symbol") == sym and t.get("action") == "Buy")

        # The assertion that actually discriminates.  Quantity and TOTAL
        # basis are identical whether or not the lot-level rescale ran —
        # the balance walker adds the shares either way and a split
        # creates no basis.  Only CONSUMING lots exposes it, so the
        # sample sells part of the position after the split:
        #
        #   rescaled   -> 20 lots @ cost/20, selling 5 relieves cost/4
        #   unrescaled -> 10 lots @ cost/10, selling 5 relieves cost/2
        sells = [t for t in txns
                 if t.get("symbol") == sym and t.get("action") == "Sell"]
        assert sells, (
            "the sample no longer sells after the split — without a "
            "disposal the rescale is unobservable and this test proves "
            "nothing (see AUDIT.md on invariance traps)"
        )
        sold_qty = sum(t["quantity"] for t in sells)
        expected_relief = cost * (sold_qty / (bought + added))
        assert sells[0]["cost_basis"] == pytest.approx(expected_relief, abs=0.05), (
            f"sale relieved {sells[0]['cost_basis']} but post-split lots "
            f"should relieve {expected_relief} — the split did not rescale "
            "per-share basis"
        )

        remaining = cost - expected_relief
        assert holding[0]["cost_basis"] == pytest.approx(remaining, abs=0.05), (
            f"a split changed total cost basis ({holding[0]['cost_basis']} vs "
            f"{remaining}) — it must only redistribute it across more shares"
        )
        assert holding[0]["quantity"] == pytest.approx(
            bought + added - sold_qty)

    def test_lot_method_override_changes_which_lot_is_relieved(self, exported):
        """`Lot Method: Coinbase = HIFO` must actually govern relief.

        The sample holds two ADA lots at very different prices, with the
        LATER one expensive, then sells exactly one lot's worth:

            FIFO -> relieves the cheap 2023 lot  -> a large GAIN
            HIFO -> relieves the dear 2024 lot   -> a small LOSS

        Both lots at one price would make the two methods agree and this
        test would prove nothing. The prices differ by 4x on purpose.

        Only Coinbase is overridden; every other account stays FIFO,
        which is what makes the effect attributable to the metadata row.
        """
        txns = exported["transactions"]
        buys = sorted((t for t in txns
                       if t.get("symbol") == "ADA-USD" and t.get("action") == "Buy"),
                      key=lambda t: t["date"])
        sells = [t for t in txns
                 if t.get("symbol") == "ADA-USD" and t.get("action") == "Sell"]
        assert len(buys) == 2 and sells, "the sample lost its ADA lot fixture"

        cheap, dear = buys[0]["amount"], buys[1]["amount"]
        assert dear > cheap * 2, (
            "the two ADA lots are no longer far enough apart in price for "
            "FIFO and HIFO to be distinguishable"
        )

        assert sells[0]["cost_basis"] == pytest.approx(dear), (
            f"the sale relieved {sells[0]['cost_basis']}, but HIFO must "
            f"relieve the DEAR lot ({dear}); relieving {cheap} means the "
            "Lot Method row was ignored and FIFO ran"
        )
        assert sells[0]["realized_gain"] < 0, (
            "under HIFO this sale is a loss; a gain means FIFO ran"
        )

        holding = [h for h in exported["holdings_by_account"]
                   if h["symbol"] == "ADA-USD"]
        assert holding[0]["cost_basis"] == pytest.approx(cheap), (
            "the cheap lot should be what remains after a HIFO relief"
        )

    def test_cost_basis_override_beats_the_fmv_estimate(self, exported):
        """A `Cost Basis` row supplies basis fin cannot reconstruct.

        The sample receives MATIC from an off-platform wallet. fin cannot
        see what it cost, so without the override the lot would take
        FMV-at-transfer basis — a documented estimate, not the truth. The
        metadata row carries the broker's customer-provided figure, and
        it must win.

        The override is deliberately DIFFERENT from the FMV so the test
        can tell which one was used.
        """
        txns = exported["transactions"]
        recv = [t for t in txns if t.get("symbol") == "MATIC-USD"]
        assert recv, "the sample lost its off-platform receive"
        row = recv[0]

        fmv = row["amount"]
        assert row["cost_basis"] != pytest.approx(fmv), (
            f"basis equals the FMV amount ({fmv}) — the Cost Basis "
            "override was not applied"
        )
        assert row["cost_basis"] == pytest.approx(1400.0), (
            "basis should be the user-supplied figure from metadata.csv"
        )

        holding = [h for h in exported["holdings_by_account"]
                   if h["symbol"] == "MATIC-USD"]
        assert holding[0]["cost_basis"] == pytest.approx(1400.0)

    def test_option_exercise_pairs_its_cash_leg(self, exported):
        """Robinhood writes an exercise as TWO rows and fin must pair them.

        The contract disposal (OEXCS, quantity "1S", no amount) carries
        no proceeds; the cash payout (OCC, "Option Maturity: Cash
        Component") carries no contract. The parser joins them on
        (date, underlying) — the OCC description is generic, so the
        instrument is the only usable key — and rolls the cash into the
        OEXCS row, dropping the OCC.

        Neither code was in the sample before, so this pairing had no
        end-to-end coverage at all.
        """
        txns = exported["transactions"]
        exercises = [t for t in txns if t.get("action") == "Option Exercise"]
        assert exercises, "the sample lost its option exercise"
        ex = exercises[0]

        assert ex["amount"] > 0, (
            "the exercise carries no proceeds — the OCC cash leg was not "
            "rolled in, so the disposal looks worthless"
        )
        assert ex["realized_gain"] == pytest.approx(
            ex["amount"] - ex["cost_basis"]), (
            "realized gain should be the cash payout minus the contract's "
            "basis"
        )
        # The OCC row must be CONSUMED, not left as a second transaction.
        assert not [t for t in txns
                    if "Cash Component" in (t.get("description") or "")], (
            "the OCC row survived as its own transaction — its cash would "
            "be counted twice"
        )
        # The contract leaves the book.
        assert not [h for h in exported["holdings_by_account"]
                    if h["symbol"] == ex["symbol"]], (
            "the exercised contract is still held"
        )

    def test_open_contract_is_floored_at_intrinsic_value(self, exported):
        """An OPEN deep-ITM contract must track its underlying.

        yfinance cannot price option contracts, so an open one is marked
        at its last traded premium — which goes stale the moment the
        underlying moves. `prices.option_intrinsic` floors that mark at
        intrinsic value from the underlying's cached close.

        CLAUDE.md records this floor shipping MISSING at three of its six
        call sites, reprinting the entire intrinsic-over-cost gap as a
        phantom daily move. The sample's only other contract expires, so
        before this fixture no valuation ever saw a live premium.
        """
        holdings = [h for h in exported["holdings_by_account"]
                    if " Call " in h["symbol"] or " Put " in h["symbol"]]
        assert holdings, "no open option contract in the sample"
        h = holdings[0]

        premium = h["cost_basis"] / h["quantity"] / 100.0
        intrinsic = self.UNDERLYING_PRICE - self.OPEN_STRIKE
        assert intrinsic > premium, (
            "fixture is not deep enough ITM for the floor to bite — the "
            "premium already exceeds intrinsic, so this proves nothing"
        )

        assert h["price"] == pytest.approx(intrinsic, abs=0.02), (
            f"contract marked at {h['price']} but intrinsic is {intrinsic}; "
            f"a mark at the {premium} purchase premium means the floor "
            "never applied"
        )
        # ...and the x100 contract multiplier is applied to the value.
        assert h["value"] == pytest.approx(
            h["quantity"] * h["price"] * 100.0, abs=0.05), (
            "option value must scale by the contract multiplier"
        )
        assert h["unrealized_gain"] > 0

    def test_pipeline_completes_and_emits_both_artifacts(
        self, isolated_workdir, sample_data, stub_prices
    ):
        import sys

        argv_save = sys.argv
        sys.argv = ["fin", "--skip-rename"]
        try:
            from src.main import main
            main()
        finally:
            sys.argv = argv_save

        exports = isolated_workdir / "exports"
        txn_json = exports / "transactions.json"
        dashboard = exports / "dashboard.html"

        assert txn_json.exists(), "pipeline produced no transactions.json"
        assert dashboard.exists(), "pipeline produced no dashboard.html"

        import json
        data = json.loads(txn_json.read_text(encoding="utf-8"))
        assert data.get("transactions"), "export carries no transactions"
        assert data.get("analytics"), "export carries no analytics block"
        # The dashboard is a single self-contained file; a truncated
        # bundle still "exists".
        assert len(dashboard.read_text(encoding="utf-8")) > 50_000
