"""Generate `audit/coverage.md` from a `coverage` run.

Line percentages alone don't say much.  The part that earns its keep is
the **never-executed function list**: a function no test ever enters is
unprotected by construction, and that list is where Segments 2/3 point
their mutation budget (a mutant on an unexecuted line survives
trivially and teaches you nothing).

Usage:

    python -m coverage run --source=src -m pytest tests/ -q
    python -m tools.audit_coverage

Writes `audit/coverage.md`.  Prints a one-line summary, not the report —
the report is for reading on disk, not for burning context.
"""

from __future__ import annotations

import ast
import os
from pathlib import Path

import coverage

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
OUT = ROOT / "audit" / "coverage.md"


def _function_spans(path: Path) -> list[tuple[str, int, list[int]]]:
    """Return (qualified_name, def_lineno, body_line_numbers) per function.

    Body lines EXCLUDE the `def` line and any decorator: those execute at
    import time regardless of whether the function is ever called, so
    counting them would mark every function as covered.
    """
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return []

    out: list[tuple[str, int, list[int]]] = []

    def walk(node: ast.AST, prefix: str) -> None:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, ast.ClassDef):
                walk(child, f"{prefix}{child.name}.")
            elif isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                body_lines: set[int] = set()
                for stmt in child.body:
                    for sub in ast.walk(stmt):
                        if hasattr(sub, "lineno"):
                            body_lines.add(sub.lineno)
                out.append((f"{prefix}{child.name}", child.lineno, sorted(body_lines)))
                walk(child, f"{prefix}{child.name}.")
            else:
                walk(child, prefix)

    walk(tree, "")
    return out


def main() -> None:
    cov = coverage.Coverage(data_file=str(ROOT / ".coverage"))
    cov.load()

    rows = []
    dead_functions: list[tuple[str, str, int, int]] = []

    for path in sorted(SRC.rglob("*.py")):
        rel = path.relative_to(ROOT).as_posix()
        try:
            _, statements, _, missing, _ = cov.analysis2(str(path))
        except coverage.misc.NoSource:
            continue

        stmts = set(statements)
        missed = set(missing)
        executed = stmts - missed
        pct = 100.0 * len(executed) / len(stmts) if stmts else 100.0
        rows.append((rel, len(stmts), len(missed), pct))

        # A function is "never executed" when none of its body statements
        # ran.  Intersect with the file's real statement lines so blank
        # lines / comments / continuation lines don't count as evidence.
        for name, lineno, body in _function_spans(path):
            real = [ln for ln in body if ln in stmts]
            if real and not any(ln in executed for ln in real):
                dead_functions.append((rel, name, lineno, len(real)))

    rows.sort(key=lambda r: (r[3], -r[1]))
    total_stmts = sum(r[1] for r in rows)
    total_missed = sum(r[2] for r in rows)
    total_pct = 100.0 * (total_stmts - total_missed) / total_stmts if total_stmts else 100.0

    lines: list[str] = []
    lines.append("# Coverage — `src/` under the full test suite\n")
    lines.append(
        "Generated by `tools/audit_coverage.py`. Regenerate with:\n\n"
        "```bash\n"
        "python -m coverage run --source=src -m pytest tests/ -q && python -m tools.audit_coverage\n"
        "```\n"
    )
    lines.append(
        f"**Overall: {total_pct:.1f}%** — {total_stmts - total_missed:,} of "
        f"{total_stmts:,} statements executed across {len(rows)} modules.\n"
    )
    lines.append(
        "> Coverage is a **floor on protection, not a measure of it**. An "
        "executed line may still be unasserted — that is what the mutation\n"
        "> segments measure. But an *unexecuted* line is unprotected by "
        "construction, so the second table below is the actionable one.\n"
    )

    lines.append("\n## Per-module line coverage\n")
    lines.append("Ascending — worst first.\n")
    lines.append("| Module | Stmts | Missed | Cover |")
    lines.append("|---|---:|---:|---:|")
    for rel, stmts, missed, pct in rows:
        lines.append(f"| `{rel}` | {stmts} | {missed} | {pct:.0f}% |")

    lines.append("\n## Functions never executed by any test\n")
    if not dead_functions:
        lines.append("_None._\n")
    else:
        by_module: dict[str, list[tuple[str, int, int]]] = {}
        for rel, name, lineno, n in dead_functions:
            by_module.setdefault(rel, []).append((name, lineno, n))
        lines.append(
            f"**{len(dead_functions)} functions** across "
            f"{len(by_module)} modules. Each is unprotected by "
            "construction: no test enters it, so no test can notice it "
            "breaking.\n"
        )
        for rel in sorted(by_module, key=lambda m: -len(by_module[m])):
            funcs = sorted(by_module[rel], key=lambda f: f[1])
            lines.append(f"\n### `{rel}` — {len(funcs)}\n")
            for name, lineno, n in funcs:
                lines.append(f"- `{name}` (line {lineno}, {n} stmts)")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(
        f"{OUT.relative_to(ROOT).as_posix()}: overall {total_pct:.1f}% "
        f"({total_stmts - total_missed:,}/{total_stmts:,} stmts), "
        f"{len(dead_functions)} never-executed functions in {len(rows)} modules"
    )


if __name__ == "__main__":
    main()
